/**
 * MCP-дескриптор модуля «Массовые реакции».
 *
 * Формат — docs/mcp/MCP-SPEC.md, правила правки — docs/mcp/MCP-CONTRIBUTING.md.
 *
 * Главная особенность, на которой ошибается оркестратор: у модуля ДВА способа задать цель —
 * список каналов (`channels`) и прямые ссылки на посты (`postUrls`), и достаточно любого
 * одного. Ссылки на посты имеют приоритет: если они заданы, каналы не используются вовсе.
 * ИИ здесь не участвует — модуль ничего не генерирует, только ставит эмодзи.
 */

/** @type {import('./index.js').ModuleDescriptor} */
export default {
  key: 'mass-react',
  version: 1,
  title: 'Mass reactions',
  platform: 'telegram',
  tags: ['reactions', 'reactions', 'emoji', 'emoji', 'involvement', 'engagement'],

  whoAmI: {
    summary: 'Places emoji reactions on posts in channels and groups on behalf of managed accounts.',
    does: [
      'if links to posts are specified, it reacts specifically to them',
      'otherwise, join the channel/group and take the LATEST post',
      'selects a random emoji from a given set and puts a reaction',
    ],
    doesNot: [
      'does not write text and does not contact AI - there is no generation here at all',
      'does not comment on posts - this is “Neurocommenting”',
      'does not select a post by content: the module has no keywords or semantics',
    ],
    requires: [
      'at least one account in a working status with a working proxy',
      'at least one of: list of channels/groups OR links to posts',
    ],
    risks:
      'Reactions are the “cheapest” module, and they are the ones that most often finish off tired accounts.'
      + 'Fatigue and routine are common to all modules, so the profile who has worked a shift'
      + 'anywhere else, it won’t get here.',
    costModel: 'Charged per action according to the price list of the module. AI tokens are not consumed - there is no generation.',
  },

  blocks: [
    {
      id: 'accounts',
      title: 'Select accounts',
      purpose: 'Which managed accounts put reactions.',
      howItWorks:
        'Accounts are moving in a circle. Busy with another task is not displayed; problematic statuses,'
        + 'fatigue, routine and daily reaction limit are skipped and recorded in the log.',
      api: { method: 'POST', path: '/api/modules/mass-react/tasks', fills: ['accountIds'] },
      params: ['accountIds'],
    },
    {
      id: 'targets',
      title: 'Goals',
      purpose: 'What to put reactions on - on channel posts or on specific posts via links.',
      howItWorks:
        'If postUrls is specified, work is carried out ONLY on these links, and channels are ignored.'
        + 'If postUrls is empty, the account enters a random channel from channels and reacts to the most'
        + 'fresh post. Posts from channels on the blacklist are eliminated.',
      api: { method: 'POST', path: '/api/modules/mass-react/tasks', fills: ['channels', 'postUrls'] },
      params: ['channels', 'postUrls'],
    },
    {
      id: 'reactions',
      title: 'Reactions',
      purpose: 'What emoji are used and how often.',
      howItWorks:
        'An emoji is selected randomly from a set for each action. Probability is applied twice:'
        + 'when selecting a post in the channel and just before sending a reaction - the actual share of actions'
        + 'turns out to be lower than specified.',
      api: { method: 'POST', path: '/api/modules/mass-react/tasks', fills: ['emojis', 'probability'] },
      params: ['emojis', 'probability'],
    },
    {
      id: 'modes',
      title: 'Operating mode',
      purpose: 'Is the task limited by the number of reactions or time?',
      howItWorks: 'By quantity - until the goal is achieved; by time - until the duration expires.',
      api: { method: 'POST', path: '/api/modules/mass-react/tasks', fills: ['workMode', 'durationMinutes'] },
      params: ['workMode', 'durationMinutes'],
    },
    {
      id: 'limits',
      title: 'Limits',
      purpose: 'How many reactions to put in total and how many with one account.',
      howItWorks: 'The actual target is a random number from [min, max], determined by the task ID.',
      api: { method: 'POST', path: '/api/modules/mass-react/tasks', fills: ['maxActions', 'minActions', 'maxPerAccount', 'minPerAccount'] },
      params: ['maxActions', 'minActions', 'maxPerAccount', 'minPerAccount'],
    },
    {
      id: 'protection',
      title: 'Account protection',
      purpose: 'Delay multiplier and action probability ceiling.',
      howItWorks: 'The protection level multiplies delays and limits the probability from above.',
      api: { method: 'POST', path: '/api/modules/mass-react/tasks', fills: ['aiProtection', 'protectionLevel'] },
      params: ['aiProtection', 'protectionLevel'],
    },
    {
      id: 'timings',
      title: 'Timings and delays',
      purpose: 'Pauses between reactions and behavior during FloodWait.',
      howItWorks: 'Pause = random from the range × protection multiplier × preset multiplier, but not less than 5 seconds.',
      api: { method: 'POST', path: '/api/modules/mass-react/tasks', fills: ['delayPreset', 'delays'] },
      params: ['delayPreset', 'delays'],
    },
    {
      id: 'binding',
      title: 'Binding',
      purpose: 'What is the purpose of the task and when does the work stop.',
      howItWorks: 'An overdue deadline stops an already ongoing task, not just new starts.',
      api: { method: 'POST', path: '/api/modules/mass-react/tasks', fills: ['goalId', 'deadline'] },
      params: ['goalId', 'deadline'],
    },
  ],

  params: [
    {
      name: 'accountIds',
      block: 'accounts',
      title: 'Accounts',
      type: 'array',
      items: 'string',
      required: true,
      minItems: 1,
      purpose: 'IDs of managed accounts that are used to set reactions.',
      constraints: ['empty list → refusal “Select at least one account”'],
      examples: [['acc_1'], ['acc_1', 'acc_2']],
      storedAs: 'task.settings.accountIds',
    },
    {
      name: 'channels',
      block: 'targets',
      title: 'Channels and groups',
      type: 'array',
      items: 'string',
      default: [],
      aliases: ['targets'],
      purpose: 'Channels and groups whose latest posts receive reactions.',
      constraints: [
        'required IF postUrls is not specified - otherwise the launch is rejected',
        'completely ignored when postUrls is given',
        'format: @username or https://t.me/<username>',
      ],
      examples: [['@durov']],
      seeAlso: ['postUrls'],
      storedAs: 'task.settings.channels (server accepts targets)',
    },
    {
      name: 'postUrls',
      block: 'targets',
      title: 'Links to posts',
      type: 'array',
      items: 'string',
      default: [],
      purpose: 'Specific posts to which you need to react.',
      constraints: [
        'format https://t.me/<channel>/<post number> or https://t.me/c/<id>/<number>',
        'has PRIORITY over channels: if the list is non-empty, channels are not used',
        'posts from blacklisted channels are discarded',
      ],
      examples: [['https://t.me/durov/342']],
      seeAlso: ['channels'],
      storedAs: 'task.settings.postUrls',
    },
    {
      name: 'emojis',
      block: 'reactions',
      title: 'Emoji set',
      type: 'array',
      items: 'string',
      default: ['👍', '❤️', '🔥'],
      purpose: 'From which the reaction to each action is randomly selected.',
      constraints: [
        'empty list = default set is used 👍 ❤️ 🔥',
        'emoji must be allowed in the channel, otherwise Telegram will reject the reaction',
      ],
      examples: [['👍'], ['👍', '🔥', '🎉']],
      storedAs: 'task.settings.emojis',
    },
    {
      name: 'probability',
      block: 'reactions',
      title: 'Probability of reaction',
      type: 'integer',
      default: 50,
      min: 0,
      max: 100,
      unit: '%',
      purpose: 'How likely is a suitable post to get a reaction?',
      constraints: [
        'with aiProtection = true, the ceiling is reduced by the level of protection: conservative ≤25%, balanced ≤45%, aggressive without limitation',
        'when working through channels, the check is performed TWICE - the actual share is approximately equal to the square of the specified',
      ],
      examples: [30, 50, 100],
      seeAlso: ['aiProtection', 'protectionLevel'],
      storedAs: 'task.settings.probability',
    },
    {
      name: 'workMode',
      block: 'modes',
      title: 'Operating mode',
      type: 'integer',
      default: 0,
      enum: [
        { value: 0, label: 'By quantity', means: 'The task continues until the goal for the number of reactions is achieved.' },
        { value: 1, label: 'By time', means: 'The task continues until durationMinutes expires.' },
      ],
      purpose: 'What is the limitation of the task?',
      constraints: ['when workMode = 1 durationMinutes is required'],
      seeAlso: ['durationMinutes', 'maxActions'],
      storedAs: 'task.settings.workMode',
    },
    {
      name: 'durationMinutes',
      block: 'modes',
      title: 'Duration',
      type: 'integer',
      default: 60,
      min: 1,
      unit: 'min',
      requiredWhen: { workMode: 1 },
      effectiveWhen: { workMode: 1 },
      purpose: 'How long does the task run in the “Timed” mode?',
      constraints: [
        'is treated as MAXIMUM: the actual duration is a random number from [min, durationMinutes],'
        + 'where min sets the protection level (60 / 45 / 30 minutes)',
      ],
      seeAlso: ['workMode', 'protectionLevel'],
      storedAs: 'task.settings.durationMinutes',
    },
    {
      name: 'maxActions',
      block: 'limits',
      title: 'Max. reactions',
      type: 'integer',
      default: 100,
      min: 1,
      aliases: ['maxComments'],
      purpose: 'Upper limit on the number of reactions per task.',
      constraints: ['must be ≥ minActions'],
      examples: [20, 200],
      seeAlso: ['minActions'],
      storedAs: 'task.settings.maxActions',
    },
    {
      name: 'minActions',
      block: 'limits',
      title: 'Min. reactions',
      type: 'integer',
      default: 0,
      min: 0,
      aliases: ['minComments'],
      purpose: 'The lower bound of the goal of the task. The actual target is a random number from [min, max].',
      constraints: ['must be ≤ maxActions'],
      seeAlso: ['maxActions'],
      storedAs: 'task.settings.minActions',
    },
    {
      name: 'maxPerAccount',
      block: 'limits',
      title: 'Max. to account',
      type: 'integer',
      default: 0,
      min: 0,
      purpose: 'Limit of reactions by one account per task.',
      constraints: [
        '0 = no account restrictions',
        'Regardless of this, the account’s daily reaction limit §6 applies (default is 200)',
      ],
      storedAs: 'task.settings.maxPerAccount',
    },
    {
      name: 'minPerAccount',
      block: 'limits',
      title: 'Min. to account',
      type: 'integer',
      default: 0,
      min: 0,
      effectiveWhen: { maxPerAccount: '*' },
      purpose: 'The lower limit of the goal per account.',
      constraints: ['must be ≤ maxPerAccount', 'only works when maxPerAccount > 0'],
      storedAs: 'task.settings.minPerAccount',
    },
    {
      name: 'aiProtection',
      block: 'protection',
      title: 'AI protection',
      type: 'boolean',
      default: true,
      purpose: 'Includes the probability ceiling from the protection level.',
      seeAlso: ['protectionLevel', 'probability'],
      storedAs: 'task.settings.aiProtection',
    },
    {
      name: 'protectionLevel',
      block: 'protection',
      title: 'Protection level',
      type: 'integer',
      default: 1,
      enum: [
        { value: 0, label: 'Conservative', means: 'Delays ×1.8, probability ≤25%, minimum duration 60 min.' },
        { value: 1, label: 'Balanced', means: 'Delays ×1, probability ≤45%, minimum duration 45 min.' },
        { value: 2, label: 'Aggressive', means: 'Delays ×0.75, probability unlimited, minimum duration 30 min.' },
      ],
      purpose: 'How carefully the account behaves.',
      constraints: ['ATTENTION: the numbering is REVERSED delayPreset - here 0 is the safest'],
      seeAlso: ['delayPreset', 'probability'],
      storedAs: 'task.settings.protectionLevel',
    },
    {
      name: 'delayPreset',
      block: 'timings',
      title: 'Tempo preset',
      type: 'integer',
      default: 1,
      enum: [
        { value: 0, label: 'Aggressive', means: 'Pauses ×0.6, duration ×0.75.' },
        { value: 1, label: 'Balanced', means: 'Basic delays ×1.' },
        { value: 2, label: 'Conservative', means: 'Pauses ×1.8, duration ×1.5.' },
        { value: 3, label: 'Custom', means: 'Delays are taken as specified, without scaling.' },
      ],
      purpose: 'Scales all task delays.',
      constraints: ['ATTENTION: the numbering is REVERSED protectionLevel - here 0 is the fastest'],
      seeAlso: ['protectionLevel', 'delays'],
      storedAs: 'task.settings.delayPreset',
    },
    {
      name: 'delays',
      block: 'timings',
      title: 'Delays',
      type: 'object',
      purpose: 'The base intervals to which the protection and preset multipliers are applied.',
      constraints: ['This module does not have a pause before the introduction - the introduction occurs without a separate delay'],
      properties: [
        {
          name: 'action',
          title: 'Pause before reaction',
          type: 'array',
          items: 'number',
          minItems: 2,
          maxItems: 2,
          default: [30, 120],
          unit: 'With',
          purpose: 'Pause range [min, max] before starting a reaction.',
          constraints: ['the actual pause is random from the range × multipliers, but not less than 5 seconds'],
        },
        {
          name: 'floodWait',
          title: 'Stock after FloodWait',
          type: 'number',
          default: 120,
          min: 0,
          unit: 'With',
          purpose: 'How long to wait beyond the duration returned by Telegram.',
        },
        {
          name: 'floodQuarantine',
          title: 'FloodWait before quarantine',
          type: 'integer',
          default: 3,
          min: 1,
          purpose: 'How many consecutive FloodWaits an account can withstand before being sent to quarantine.',
        },
      ],
      storedAs: 'task.settings.delays',
    },
    {
      name: 'goalId',
      block: 'binding',
      title: 'Target',
      type: 'string',
      purpose: 'The goal to which the task relates.',
      constraints: [
        'does not affect the content of reactions - the module does not generate generation',
        'used for deadlines and reporting; an expired goal stops the task',
      ],
      seeAlso: ['deadline'],
      storedAs: 'task.settings.goalId',
    },
    {
      name: 'deadline',
      block: 'binding',
      title: 'Deadline',
      type: 'string',
      pattern: '^\\d{4}-\\d{2}-\\d{2}$',
      purpose: 'The date after which work on the task stops.',
      constraints: [
        'format YYYY-MM-DD; deadline includes the entire specified day',
        'comes from campaign; if not specified, the goal deadline is taken by goalId',
        'stops an ALREADY RUNNING task',
      ],
      examples: ['2026-09-01'],
      seeAlso: ['goalId'],
      storedAs: 'task.settings.deadline',
    },
  ],

  presets: [
    {
      param: 'delayPreset',
      title: 'Tempo preset',
      source: 'server/lib/protection.js — PRESET_MUL',
      values: [
        { value: 0, label: 'Aggressive', multiplier: 0.6, means: 'Pauses ×0.6, duration ×0.75.', useWhen: 'warmed up “expenditure” accounts' },
        { value: 1, label: 'Balanced', multiplier: 1, means: 'Basic delays.', useWhen: 'daily work' },
        { value: 2, label: 'Conservative', multiplier: 1.8, means: 'Pauses ×1.8, duration ×1.5.', useWhen: 'new and expensive accounts' },
        { value: 3, label: 'Custom', multiplier: 1, means: 'No scaling.', useWhen: 'manual setting' },
      ],
    },
    {
      param: 'protectionLevel',
      title: 'Protection level',
      source: 'server/lib/protection.js — LEVEL_MUL + effectiveProbability; server/lib/workModeDuration.js',
      values: [
        { value: 0, label: 'Conservative', multiplier: 1.8, probabilityCap: 25, minDurationMinutes: 60, means: 'Delays ×1.8, probability ≤25%.' },
        { value: 1, label: 'Balanced', multiplier: 1, probabilityCap: 45, minDurationMinutes: 45, means: 'Delays ×1, probability ≤45%.' },
        { value: 2, label: 'Aggressive', multiplier: 0.75, probabilityCap: 100, minDurationMinutes: 30, means: 'Delays ×0.75, unlimited probability.' },
      ],
    },
  ],

  examples: [
    {
      title: 'Reactions to specific posts',
      when: 'need to support several well-known publications',
      input: {
        accountIds: ['acc_1', 'acc_2'],
        postUrls: ['https://t.me/durov/342', 'https://t.me/durov/343'],
        emojis: ['👍', '🔥'],
        maxActions: 10,
        probability: 100,
        protectionLevel: 1,
        delayPreset: 1,
      },
    },
    {
      title: 'Background activity by channel',
      when: 'you need an even presence on fresh posts of several channels',
      input: {
        accountIds: ['acc_1', 'acc_2', 'acc_3'],
        channels: ['@channel_one', '@channel_two'],
        emojis: ['👍', '❤️', '🔥'],
        workMode: 1,
        durationMinutes: 480,
        maxPerAccount: 15,
        probability: 70,
        protectionLevel: 0,
        delayPreset: 2,
      },
    },
  ],

  contract: {
    sources: [
      { file: 'server/modules/workers.js', symbols: ['runMassReact', 'targets', 'goalExpired'] },
      { file: 'server/lib/targets.js', symbols: ['resolveTotalTarget', 'resolvePerAccountTarget'] },
      { file: 'server/lib/accountRunner.js', symbols: ['totalLimitReached', 'perAccountLimitReached', 'handleFlood'] },
      { file: 'server/lib/workModeDuration.js', symbols: ['resolveDurationPeriodMinutes'] },
    ],
    ignore: ['initiator', 'userId'],
  },
}
