/**
 * MCP-дескриптор модуля «Масслукинг».
 *
 * Формат — docs/mcp/MCP-SPEC.md, правила правки — docs/mcp/MCP-CONTRIBUTING.md.
 *
 * Самый безобидный из боевых модулей: только просмотры, ничего не публикует и не пишет.
 * Главное, что должен понимать оркестратор — режим определяет, ЧТО именно смотрят
 * (истории, посты или оба), и от этого зависит, кого имеет смысл ставить целью.
 */

/** @type {import('./index.js').ModuleDescriptor} */
export default {
  key: 'mass-looking',
  version: 1,
  title: 'Масслукинг',
  platform: 'telegram',
  tags: ['просмотры', 'views', 'сторис', 'stories', 'масслукинг', 'охват'],

  whoAmI: {
    summary: 'Массово просматривает истории и посты выбранных пользователей и каналов от имени управляемых аккаунтов.',
    does: [
      'отмечает истории пользователя как просмотренные — автор видит, кто заходил',
      'просматривает последние посты канала (глубина настраивается)',
      'умеет и то и другое сразу',
    ],
    doesNot: [
      'ничего не публикует: ни комментариев, ни реакций, ни сообщений',
      'не обращается к ИИ и не тратит токены',
      'не вступает в приватные каналы',
    ],
    requires: ['минимум один аккаунт с рабочим прокси', 'минимум одна цель'],
    risks:
      'Низкий риск: просмотры Telegram почти не ограничивает. Основной сценарий использования — '
      + 'мягко привлечь внимание владельца историй тем, что его посмотрели.',
    costModel: 'Списывается за действие по прайсу модуля. Токены ИИ не расходуются.',
  },

  blocks: [
    {
      id: 'accounts',
      title: 'Выберите аккаунты',
      purpose: 'Какими аккаунтами смотреть.',
      howItWorks: 'Аккаунты перебираются по кругу; занятые другой задачей и проблемные пропускаются.',
      api: { method: 'POST', path: '/api/modules/mass-looking/tasks', fills: ['accountIds'] },
      params: ['accountIds'],
    },
    {
      id: 'targets',
      title: 'Кого смотреть',
      purpose: 'Пользователи и каналы, чей контент просматривают.',
      howItWorks: 'Цель выбирается случайно на каждой итерации. Цели из чёрного списка отсеиваются.',
      api: { method: 'POST', path: '/api/modules/mass-looking/tasks', fills: ['channels'] },
      params: ['channels'],
    },
    {
      id: 'mode',
      title: 'Что смотреть',
      purpose: 'Истории, посты или и то и другое.',
      howItWorks:
        'Истории есть только у пользователей и не у всех; посты — у каналов. Режим стоит выбирать '
        + 'под тип целей, иначе задача будет вхолостую перебирать цели без подходящего контента.',
      api: { method: 'POST', path: '/api/modules/mass-looking/tasks', fills: ['lookMode', 'lookPostsCount'] },
      params: ['lookMode', 'lookPostsCount'],
    },
    {
      id: 'limits',
      title: 'Лимиты',
      purpose: 'Сколько просмотров сделать всего и одним аккаунтом.',
      howItWorks: 'Фактическая цель — случайное число из [min, max], детерминированное по ID задачи.',
      api: {
        method: 'POST',
        path: '/api/modules/mass-looking/tasks',
        fills: ['maxActions', 'minActions', 'maxPerAccount', 'minPerAccount'],
      },
      params: ['maxActions', 'minActions', 'maxPerAccount', 'minPerAccount'],
    },
    {
      id: 'modes',
      title: 'Режим работы',
      purpose: 'Чем ограничена задача — числом просмотров или временем.',
      howItWorks: 'По количеству — до достижения цели; по времени — до истечения длительности.',
      api: { method: 'POST', path: '/api/modules/mass-looking/tasks', fills: ['workMode', 'durationMinutes'] },
      params: ['workMode', 'durationMinutes'],
    },
    {
      id: 'protection',
      title: 'Защита аккаунтов',
      purpose: 'Множитель задержек.',
      howItWorks: 'Уровень защиты умножает паузы между просмотрами. Вероятности у модуля нет.',
      api: { method: 'POST', path: '/api/modules/mass-looking/tasks', fills: ['protectionLevel', 'delayPreset'] },
      params: ['protectionLevel', 'delayPreset'],
    },
    {
      id: 'timings',
      title: 'Тайминги и задержки',
      purpose: 'Паузы между просмотрами и поведение при FloodWait.',
      howItWorks: 'Пауза = случайная из диапазона × множители, но не меньше 5 секунд.',
      api: { method: 'POST', path: '/api/modules/mass-looking/tasks', fills: ['delays'] },
      params: ['delays'],
    },
    {
      id: 'binding',
      title: 'Привязка',
      purpose: 'К какой цели относится задача и когда работа прекращается.',
      howItWorks: 'Просроченный дедлайн останавливает уже идущую задачу.',
      api: { method: 'POST', path: '/api/modules/mass-looking/tasks', fills: ['goalId', 'deadline'] },
      params: ['goalId', 'deadline'],
    },
  ],

  params: [
    {
      name: 'accountIds',
      block: 'accounts',
      title: 'Аккаунты',
      type: 'array',
      items: 'string',
      required: true,
      minItems: 1,
      purpose: 'ID аккаунтов, которыми выполняются просмотры.',
      constraints: ['пустой список → отказ «Выберите хотя бы один аккаунт»'],
      examples: [['acc_1']],
      storedAs: 'task.settings.accountIds',
    },
    {
      name: 'channels',
      block: 'targets',
      title: 'Цели',
      type: 'array',
      items: 'string',
      required: true,
      minItems: 1,
      aliases: ['targets'],
      purpose: 'Пользователи и каналы, чьи истории и посты просматриваются.',
      constraints: [
        'формат: @username или https://t.me/<username>',
        'истории есть только у пользователей, посты — у каналов: подбирайте цели под режим',
      ],
      examples: [['@durov'], ['@some_user', '@some_channel']],
      seeAlso: ['lookMode'],
      storedAs: 'task.settings.channels (сервер принимает и targets)',
    },
    {
      name: 'lookMode',
      block: 'mode',
      title: 'Что смотреть',
      type: 'string',
      default: 'stories',
      enum: [
        { value: 'stories', label: 'Истории', means: 'Отмечает истории цели как просмотренные — владелец видит, кто заходил.' },
        { value: 'posts', label: 'Посты', means: 'Просматривает последние посты канала в количестве lookPostsCount.' },
        { value: 'both', label: 'Истории и посты', means: 'Сначала истории, затем посты.' },
      ],
      purpose: 'Какой контент просматривается у цели.',
      constraints: ['неизвестное значение молча заменяется на stories'],
      seeAlso: ['lookPostsCount', 'channels'],
      storedAs: 'task.settings.lookMode',
    },
    {
      name: 'lookPostsCount',
      block: 'mode',
      title: 'Сколько постов смотреть',
      type: 'integer',
      default: 3,
      min: 1,
      max: 50,
      effectiveWhen: { lookMode: 'posts' },
      purpose: 'Глубина просмотра постов у одной цели.',
      constraints: [
        'значение вне 1…50 приводится к границе',
        'в режиме stories не используется; в режиме both — используется',
      ],
      examples: [3, 10],
      seeAlso: ['lookMode'],
      storedAs: 'task.settings.lookPostsCount',
    },
    {
      name: 'maxActions',
      block: 'limits',
      title: 'Макс. просмотров',
      type: 'integer',
      default: 100,
      min: 1,
      aliases: ['maxComments'],
      purpose: 'Верхняя граница числа просмотров за задачу.',
      constraints: ['должен быть ≥ minActions'],
      seeAlso: ['minActions'],
      storedAs: 'task.settings.maxActions',
    },
    {
      name: 'minActions',
      block: 'limits',
      title: 'Мин. просмотров',
      type: 'integer',
      default: 0,
      min: 0,
      aliases: ['minComments'],
      purpose: 'Нижняя граница цели задачи.',
      constraints: ['должен быть ≤ maxActions'],
      seeAlso: ['maxActions'],
      storedAs: 'task.settings.minActions',
    },
    {
      name: 'maxPerAccount',
      block: 'limits',
      title: 'Макс. на аккаунт',
      type: 'integer',
      default: 0,
      min: 0,
      purpose: 'Потолок просмотров одним аккаунтом за задачу.',
      constraints: ['0 = ограничения на аккаунт нет'],
      storedAs: 'task.settings.maxPerAccount',
    },
    {
      name: 'minPerAccount',
      block: 'limits',
      title: 'Мин. на аккаунт',
      type: 'integer',
      default: 0,
      min: 0,
      effectiveWhen: { maxPerAccount: '*' },
      purpose: 'Нижняя граница цели на один аккаунт.',
      constraints: ['работает только когда maxPerAccount > 0'],
      storedAs: 'task.settings.minPerAccount',
    },
    {
      name: 'workMode',
      block: 'modes',
      title: 'Режим работы',
      type: 'integer',
      default: 0,
      enum: [
        { value: 0, label: 'По количеству', means: 'До достижения цели по числу просмотров.' },
        { value: 1, label: 'По времени', means: 'До истечения durationMinutes.' },
      ],
      purpose: 'Чем ограничена задача.',
      constraints: ['при workMode = 1 обязателен durationMinutes'],
      seeAlso: ['durationMinutes'],
      storedAs: 'task.settings.workMode',
    },
    {
      name: 'durationMinutes',
      block: 'modes',
      title: 'Длительность',
      type: 'integer',
      default: 60,
      min: 1,
      unit: 'мин',
      requiredWhen: { workMode: 1 },
      effectiveWhen: { workMode: 1 },
      purpose: 'Сколько задача работает в режиме «По времени».',
      constraints: [
        'трактуется как МАКСИМУМ: минимум задаёт уровень защиты (60 / 45 / 30 минут)',
      ],
      seeAlso: ['workMode', 'protectionLevel'],
      storedAs: 'task.settings.durationMinutes',
    },
    {
      name: 'protectionLevel',
      block: 'protection',
      title: 'Уровень защиты',
      type: 'integer',
      default: 1,
      enum: [
        { value: 0, label: 'Консервативный', means: 'Задержки ×1.8, минимальная длительность 60 мин.' },
        { value: 1, label: 'Сбалансированный', means: 'Задержки ×1, минимальная длительность 45 мин.' },
        { value: 2, label: 'Агрессивный', means: 'Задержки ×0.75, минимальная длительность 30 мин.' },
      ],
      purpose: 'Насколько осторожно ведёт себя аккаунт.',
      constraints: ['ВНИМАНИЕ: нумерация ОБРАТНА delayPreset — здесь 0 самый безопасный'],
      seeAlso: ['delayPreset'],
      storedAs: 'task.settings.protectionLevel',
    },
    {
      name: 'delayPreset',
      block: 'protection',
      title: 'Пресет темпа',
      type: 'integer',
      default: 1,
      enum: [
        { value: 0, label: 'Агрессивный', means: 'Паузы ×0.6.' },
        { value: 1, label: 'Сбалансированный', means: 'Базовые задержки ×1.' },
        { value: 2, label: 'Консервативный', means: 'Паузы ×1.8.' },
        { value: 3, label: 'Custom', means: 'Без масштабирования.' },
      ],
      purpose: 'Масштабирует паузы между просмотрами.',
      constraints: ['ВНИМАНИЕ: нумерация ОБРАТНА protectionLevel — здесь 0 самый быстрый'],
      seeAlso: ['protectionLevel', 'delays'],
      storedAs: 'task.settings.delayPreset',
    },
    {
      name: 'delays',
      block: 'timings',
      title: 'Задержки',
      type: 'object',
      purpose: 'Базовые интервалы, к которым применяются множители.',
      properties: [
        {
          name: 'action',
          title: 'Пауза между просмотрами',
          type: 'array',
          items: 'number',
          minItems: 2,
          maxItems: 2,
          default: [30, 120],
          unit: 'с',
          purpose: 'Диапазон [мин, макс] паузы между просмотрами.',
          constraints: ['фактическая пауза — случайная из диапазона × множители, но не меньше 5 секунд'],
        },
        {
          name: 'floodWait',
          title: 'Запас после FloodWait',
          type: 'number',
          default: 120,
          min: 0,
          unit: 'с',
          purpose: 'Сколько ждать сверх длительности, которую вернул Telegram.',
        },
        {
          name: 'floodQuarantine',
          title: 'FloodWait до карантина',
          type: 'integer',
          default: 3,
          min: 1,
          purpose: 'Сколько FloodWait подряд выдерживает аккаунт до карантина.',
        },
      ],
      storedAs: 'task.settings.delays',
    },
    {
      name: 'goalId',
      block: 'binding',
      title: 'Цель',
      type: 'string',
      purpose: 'Цель, к которой относится задача.',
      constraints: ['на поведение просмотров не влияет — используется для дедлайна и отчётности'],
      seeAlso: ['deadline'],
      storedAs: 'task.settings.goalId',
    },
    {
      name: 'deadline',
      block: 'binding',
      title: 'Дедлайн',
      type: 'string',
      pattern: '^\\d{4}-\\d{2}-\\d{2}$',
      purpose: 'Дата, после которой работа прекращается.',
      constraints: ['формат YYYY-MM-DD', 'останавливает УЖЕ ИДУЩУЮ задачу'],
      examples: ['2026-09-01'],
      seeAlso: ['goalId'],
      storedAs: 'task.settings.deadline',
    },
  ],

  presets: [
    {
      param: 'delayPreset',
      title: 'Пресет темпа',
      source: 'server/lib/protection.js — PRESET_MUL',
      values: [
        { value: 0, label: 'Агрессивный', multiplier: 0.6, means: 'Паузы ×0.6.', useWhen: 'нужен объём быстро' },
        { value: 1, label: 'Сбалансированный', multiplier: 1, means: 'Базовые задержки.', useWhen: 'обычная работа' },
        { value: 2, label: 'Консервативный', multiplier: 1.8, means: 'Паузы ×1.8.', useWhen: 'новые аккаунты' },
        { value: 3, label: 'Custom', multiplier: 1, means: 'Без масштабирования.', useWhen: 'ручная настройка' },
      ],
    },
    {
      param: 'protectionLevel',
      title: 'Уровень защиты',
      source: 'server/lib/protection.js — LEVEL_MUL; server/lib/workModeDuration.js',
      values: [
        { value: 0, label: 'Консервативный', multiplier: 1.8, minDurationMinutes: 60, means: 'Задержки ×1.8.' },
        { value: 1, label: 'Сбалансированный', multiplier: 1, minDurationMinutes: 45, means: 'Задержки ×1.' },
        { value: 2, label: 'Агрессивный', multiplier: 0.75, minDurationMinutes: 30, means: 'Задержки ×0.75.' },
      ],
    },
  ],

  examples: [
    {
      title: 'Просмотр историй, чтобы о нас узнали',
      when: 'нужно мягко привлечь внимание аудитории',
      input: {
        accountIds: ['acc_1', 'acc_2'],
        channels: ['@user_one', '@user_two'],
        lookMode: 'stories',
        maxActions: 50,
        protectionLevel: 1,
        delayPreset: 1,
      },
    },
    {
      title: 'Набор просмотров на постах канала',
      when: 'нужны просмотры на свежих публикациях',
      input: {
        accountIds: ['acc_1'],
        channels: ['@some_channel'],
        lookMode: 'posts',
        lookPostsCount: 10,
        workMode: 1,
        durationMinutes: 120,
        protectionLevel: 0,
      },
    },
  ],

  contract: {
    sources: [
      { file: 'server/modules/workers.js', symbols: ['runMassLooking', 'targets', 'goalExpired'] },
      { file: 'server/lib/targets.js', symbols: ['resolveTotalTarget', 'resolvePerAccountTarget'] },
      { file: 'server/lib/accountRunner.js', symbols: ['totalLimitReached', 'perAccountLimitReached', 'handleFlood'] },
      { file: 'server/lib/workModeDuration.js', symbols: ['resolveDurationPeriodMinutes'] },
    ],
    ignore: ['initiator', 'userId'],
  },
}
