/**
 * MCP-дескриптор модуля «Масслукинг».
 *
 * Формат — docs/mcp/MCP-SPEC.md, правила правки — docs/mcp/MCP-CONTRIBUTING.md.
 *
 * Самый безобидный из боевых модулей: только просмотры, ничего не публикует и не пишет.
 * Главное, что должен понимать оркестратор — режим определяет, ЧТО именно смотрят
 * (истории, посты или оба), и от этого зависит, кого имеет смысл ставить целью.
 */

/** @type {import('./index.js').ModuleDescriptor} */
export default {
  key: 'mass-looking',
  version: 1,
  // ИИ не участвует: генерации нет, токены модели не тратятся (см. costModel).
  usesAi: false,
  title: 'Masslooking',
  platform: 'telegram',
  tags: ['views', 'views', 'stories', 'stories', 'masslooking', 'coverage'],

  whoAmI: {
    summary: 'Massively views stories and posts of selected users and channels on behalf of managed accounts.',
    does: [
      'marks user stories as viewed - the author sees who visited',
      'views the latest posts of the channel (depth is adjustable)',
      'can do both at once',
    ],
    doesNot: [
      'does not publish anything: no comments, no reactions, no messages',
      'does not contact AI and does not spend tokens',
      'does not enter private channels',
    ],
    requires: ['at least one account with a working proxy', 'at least one target'],
    risks:
      'Low risk: Telegram views are almost unlimited. Main use case −'
      + 'gently attract the attention of the owner of the stories by being watched.',
    costModel: 'Charged per action according to the price list of the module. AI tokens are not consumed.',
  },

  blocks: [
    {
      id: 'accounts',
      title: 'Select accounts',
      purpose: 'Which accounts to look at.',
      howItWorks: 'Accounts are moved in a circle; busy with another task and problematic ones are skipped.',
      api: { method: 'POST', path: '/api/modules/mass-looking/tasks', fills: ['accountIds'] },
      params: ['accountIds'],
    },
    {
      id: 'targets',
      title: 'Who to watch',
      purpose: 'Users and channels whose content is viewed.',
      howItWorks: 'The target is chosen randomly at each iteration. Targets from the blacklist are eliminated.',
      api: { method: 'POST', path: '/api/modules/mass-looking/tasks', fills: ['channels'] },
      params: ['channels'],
    },
    {
      id: 'mode',
      title: 'What to watch',
      purpose: 'Stories, posts, or both.',
      howItWorks:
        'Only users have stories and not everyone has them; posts are at the channels. The mode is worth choosing'
        + 'according to the type of goals, otherwise the task will idlely sort through goals without suitable content.',
      api: { method: 'POST', path: '/api/modules/mass-looking/tasks', fills: ['lookMode', 'lookPostsCount'] },
      params: ['lookMode', 'lookPostsCount'],
    },
    {
      id: 'limits',
      title: 'Limits',
      purpose: 'How many views can you make in total with one account?',
      howItWorks: 'The actual target is a random number from [min, max], determined by the task ID.',
      api: {
        method: 'POST',
        path: '/api/modules/mass-looking/tasks',
        fills: ['maxActions', 'minActions', 'maxPerAccount', 'minPerAccount'],
      },
      params: ['maxActions', 'minActions', 'maxPerAccount', 'minPerAccount'],
    },
    {
      id: 'modes',
      title: 'Operating mode',
      purpose: 'Is the task limited by the number of views or time?',
      howItWorks: 'By quantity - until the goal is achieved; by time - until the duration expires.',
      api: { method: 'POST', path: '/api/modules/mass-looking/tasks', fills: ['workMode', 'durationMinutes'] },
      params: ['workMode', 'durationMinutes'],
    },
    {
      id: 'protection',
      title: 'Account protection',
      purpose: 'Delay multiplier.',
      howItWorks: 'The level of protection increases the pauses between views. The module has no probability.',
      api: { method: 'POST', path: '/api/modules/mass-looking/tasks', fills: ['protectionLevel', 'delayPreset'] },
      params: ['protectionLevel', 'delayPreset'],
    },
    {
      id: 'timings',
      title: 'Timings and delays',
      purpose: 'Pauses between views and FloodWait behavior.',
      howItWorks: 'Pause = random from the range × multipliers, but not less than 5 seconds.',
      api: { method: 'POST', path: '/api/modules/mass-looking/tasks', fills: ['delays'] },
      params: ['delays'],
    },
    {
      id: 'binding',
      title: 'Binding',
      purpose: 'What is the purpose of the task and when does the work stop.',
      howItWorks: 'An overdue deadline stops an already ongoing task.',
      api: { method: 'POST', path: '/api/modules/mass-looking/tasks', fills: ['goalId', 'deadline'] },
      params: ['goalId', 'deadline'],
    },
  ],

  params: [
    {
      name: 'accountIds',
      block: 'accounts',
      title: 'Accounts',
      type: 'array',
      items: 'string',
      required: true,
      minItems: 1,
      purpose: 'Account IDs that perform views.',
      constraints: ['empty list → refusal “Select at least one account”'],
      examples: [['acc_1']],
      storedAs: 'task.settings.accountIds',
    },
    {
      name: 'channels',
      block: 'targets',
      title: 'Goals',
      type: 'array',
      items: 'string',
      required: true,
      minItems: 1,
      aliases: ['targets'],
      purpose: 'Users and channels whose stories and posts are viewed.',
      constraints: [
        'format: @username or https://t.me/<username>',
        'Only users have stories, channels have posts: select goals for the mode',
      ],
      examples: [['@durov'], ['@some_user', '@some_channel']],
      seeAlso: ['lookMode'],
      storedAs: 'task.settings.channels (server accepts targets)',
    },
    {
      name: 'lookMode',
      block: 'mode',
      title: 'What to watch',
      type: 'string',
      default: 'stories',
      enum: [
        { value: 'stories', label: 'Stories', means: "Marks the target's stories as viewed - the owner sees who visited." },
        { value: 'posts', label: 'Posts', means: 'Views the latest posts of the channel in the lookPostsCount amount.' },
        { value: 'both', label: 'Stories and posts', means: 'First stories, then posts.' },
      ],
      purpose: 'What content is being viewed by the target.',
      constraints: ['the unknown value is silently replaced by stories'],
      seeAlso: ['lookPostsCount', 'channels'],
      storedAs: 'task.settings.lookMode',
    },
    {
      name: 'lookPostsCount',
      block: 'mode',
      title: 'How many posts to watch',
      type: 'integer',
      default: 3,
      min: 1,
      max: 50,
      effectiveWhen: { lookMode: 'posts' },
      purpose: 'Depth of viewing posts for one target.',
      constraints: [
        'value outside 1…50 is brought to the limit',
        'not used in stories mode; in both mode - used',
      ],
      examples: [3, 10],
      seeAlso: ['lookMode'],
      storedAs: 'task.settings.lookPostsCount',
    },
    {
      name: 'maxActions',
      block: 'limits',
      title: 'Max. views',
      type: 'integer',
      default: 100,
      min: 1,
      aliases: ['maxComments'],
      purpose: 'Upper limit on the number of views per task.',
      constraints: ['must be ≥ minActions'],
      seeAlso: ['minActions'],
      storedAs: 'task.settings.maxActions',
    },
    {
      name: 'minActions',
      block: 'limits',
      title: 'Min. views',
      type: 'integer',
      default: 0,
      min: 0,
      aliases: ['minComments'],
      purpose: 'The lower bound of the goal of the task.',
      constraints: ['must be ≤ maxActions'],
      seeAlso: ['maxActions'],
      storedAs: 'task.settings.minActions',
    },
    {
      name: 'maxPerAccount',
      block: 'limits',
      title: 'Max. to account',
      type: 'integer',
      default: 0,
      min: 0,
      purpose: 'Limit of views per account per task.',
      constraints: ['0 = no account restrictions'],
      storedAs: 'task.settings.maxPerAccount',
    },
    {
      name: 'minPerAccount',
      block: 'limits',
      title: 'Min. to account',
      type: 'integer',
      default: 0,
      min: 0,
      effectiveWhen: { maxPerAccount: '*' },
      purpose: 'The lower limit of the goal per account.',
      constraints: ['only works when maxPerAccount > 0'],
      storedAs: 'task.settings.minPerAccount',
    },
    {
      name: 'workMode',
      block: 'modes',
      title: 'Operating mode',
      type: 'integer',
      default: 0,
      enum: [
        { value: 0, label: 'By quantity', means: 'Until the viewership goal is reached.' },
        { value: 1, label: 'By time', means: 'Until durationMinutes expires.' },
      ],
      purpose: 'What is the limitation of the task?',
      constraints: ['when workMode = 1 durationMinutes is required'],
      seeAlso: ['durationMinutes'],
      storedAs: 'task.settings.workMode',
    },
    {
      name: 'durationMinutes',
      block: 'modes',
      title: 'Duration',
      type: 'integer',
      default: 60,
      min: 1,
      unit: 'min',
      requiredWhen: { workMode: 1 },
      effectiveWhen: { workMode: 1 },
      purpose: 'How long does the task run in the “Timed” mode?',
      constraints: [
        'interpreted as MAXIMUM: minimum sets the level of protection (60 / 45 / 30 minutes)',
      ],
      seeAlso: ['workMode', 'protectionLevel'],
      storedAs: 'task.settings.durationMinutes',
    },
    {
      name: 'protectionLevel',
      block: 'protection',
      title: 'Protection level',
      type: 'integer',
      default: 1,
      enum: [
        { value: 0, label: 'Conservative', means: 'Delays ×1.8, minimum duration 60 min.' },
        { value: 1, label: 'Balanced', means: 'Delays ×1, minimum duration 45 min.' },
        { value: 2, label: 'Aggressive', means: 'Delays ×0.75, minimum duration 30 min.' },
      ],
      purpose: 'How carefully the account behaves.',
      constraints: ['ATTENTION: the numbering is REVERSED delayPreset - here 0 is the safest'],
      seeAlso: ['delayPreset'],
      storedAs: 'task.settings.protectionLevel',
    },
    {
      name: 'delayPreset',
      block: 'protection',
      title: 'Tempo preset',
      type: 'integer',
      default: 1,
      enum: [
        { value: 0, label: 'Aggressive', means: 'Pauses ×0.6.' },
        { value: 1, label: 'Balanced', means: 'Basic delays ×1.' },
        { value: 2, label: 'Conservative', means: 'Pauses ×1.8.' },
        { value: 3, label: 'Custom', means: 'No scaling.' },
      ],
      purpose: 'Scales pauses between views.',
      constraints: ['ATTENTION: the numbering is REVERSED protectionLevel - here 0 is the fastest'],
      seeAlso: ['protectionLevel', 'delays'],
      storedAs: 'task.settings.delayPreset',
    },
    {
      name: 'delays',
      block: 'timings',
      title: 'Delays',
      type: 'object',
      purpose: 'The base intervals to which the multipliers are applied.',
      properties: [
        {
          name: 'action',
          title: 'Pause between views',
          type: 'array',
          items: 'number',
          minItems: 2,
          maxItems: 2,
          default: [30, 120],
          unit: 'With',
          purpose: 'Range [min, max] of pause between views.',
          constraints: ['the actual pause is random from the range × multipliers, but not less than 5 seconds'],
        },
        {
          name: 'floodWait',
          title: 'Stock after FloodWait',
          type: 'number',
          default: 120,
          min: 0,
          unit: 'With',
          purpose: 'How long to wait beyond the duration returned by Telegram.',
        },
        {
          name: 'floodQuarantine',
          title: 'FloodWait before quarantine',
          type: 'integer',
          default: 3,
          min: 1,
          purpose: 'How many consecutive FloodWaits the account can withstand before quarantine.',
        },
      ],
      storedAs: 'task.settings.delays',
    },
    {
      name: 'goalId',
      block: 'binding',
      title: 'Target',
      type: 'string',
      purpose: 'The goal to which the task relates.',
      constraints: ['does not affect viewing behavior - used for deadlines and reporting'],
      seeAlso: ['deadline'],
      storedAs: 'task.settings.goalId',
    },
    {
      name: 'deadline',
      block: 'binding',
      title: 'Deadline',
      type: 'string',
      pattern: '^\\d{4}-\\d{2}-\\d{2}$',
      purpose: 'The date after which work ceases.',
      constraints: ['format YYYY-MM-DD', 'stops an ALREADY RUNNING task'],
      examples: ['2026-09-01'],
      seeAlso: ['goalId'],
      storedAs: 'task.settings.deadline',
    },
  ],

  presets: [
    {
      param: 'delayPreset',
      title: 'Tempo preset',
      source: 'server/lib/protection.js — PRESET_MUL',
      values: [
        { value: 0, label: 'Aggressive', multiplier: 0.6, means: 'Pauses ×0.6.', useWhen: 'need volume quickly' },
        { value: 1, label: 'Balanced', multiplier: 1, means: 'Basic delays.', useWhen: 'regular work' },
        { value: 2, label: 'Conservative', multiplier: 1.8, means: 'Pauses ×1.8.', useWhen: 'new accounts' },
        { value: 3, label: 'Custom', multiplier: 1, means: 'No scaling.', useWhen: 'manual setting' },
      ],
    },
    {
      param: 'protectionLevel',
      title: 'Protection level',
      source: 'server/lib/protection.js — LEVEL_MUL; server/lib/workModeDuration.js',
      values: [
        { value: 0, label: 'Conservative', multiplier: 1.8, minDurationMinutes: 60, means: 'Delays ×1.8.' },
        { value: 1, label: 'Balanced', multiplier: 1, minDurationMinutes: 45, means: 'Delays ×1.' },
        { value: 2, label: 'Aggressive', multiplier: 0.75, minDurationMinutes: 30, means: 'Delays ×0.75.' },
      ],
    },
  ],

  examples: [
    {
      title: 'View stories to let people know about us',
      when: "need to gently attract the audience's attention",
      input: {
        accountIds: ['acc_1', 'acc_2'],
        channels: ['@user_one', '@user_two'],
        lookMode: 'stories',
        maxActions: 50,
        protectionLevel: 1,
        delayPreset: 1,
      },
    },
    {
      title: 'Set of views on channel posts',
      when: 'Need views on new publications',
      input: {
        accountIds: ['acc_1'],
        channels: ['@some_channel'],
        lookMode: 'posts',
        lookPostsCount: 10,
        workMode: 1,
        durationMinutes: 120,
        protectionLevel: 0,
      },
    },
  ],

  contract: {
    sources: [
      { file: 'server/modules/workers.js', symbols: ['runMassLooking', 'targets', 'goalExpired'] },
      { file: 'server/lib/targets.js', symbols: ['resolveTotalTarget', 'resolvePerAccountTarget'] },
      { file: 'server/lib/accountRunner.js', symbols: ['totalLimitReached', 'perAccountLimitReached', 'handleFlood'] },
      { file: 'server/lib/workModeDuration.js', symbols: ['resolveDurationPeriodMinutes'] },
    ],
    ignore: ['initiator', 'userId'],
  },
}
