/**
 * MCP-дескриптор модуля «Массовые реакции».
 *
 * Формат — docs/mcp/MCP-SPEC.md, правила правки — docs/mcp/MCP-CONTRIBUTING.md.
 *
 * Главная особенность, на которой ошибается оркестратор: у модуля ДВА способа задать цель —
 * список каналов (`channels`) и прямые ссылки на посты (`postUrls`), и достаточно любого
 * одного. Ссылки на посты имеют приоритет: если они заданы, каналы не используются вовсе.
 * ИИ здесь не участвует — модуль ничего не генерирует, только ставит эмодзи.
 */

/** @type {import('./index.js').ModuleDescriptor} */
export default {
  key: 'mass-react',
  version: 1,
  title: 'Массовые реакции',
  platform: 'telegram',
  tags: ['реакции', 'reactions', 'эмодзи', 'emoji', 'вовлечение', 'engagement'],

  whoAmI: {
    summary: 'Ставит эмодзи-реакции на посты в каналах и группах от имени управляемых аккаунтов.',
    does: [
      'если заданы ссылки на посты — реагирует именно на них',
      'иначе вступает в канал/группу и берёт САМЫЙ СВЕЖИЙ пост',
      'выбирает случайный эмодзи из заданного набора и ставит реакцию',
    ],
    doesNot: [
      'не пишет текст и не обращается к ИИ — генерации здесь нет вообще',
      'не комментирует посты — это «Нейрокомментинг»',
      'не выбирает пост по содержанию: ни ключевых слов, ни семантики у модуля нет',
    ],
    requires: [
      'минимум один аккаунт в статусе, допускающем работу, с рабочим прокси',
      'хотя бы одно из: список каналов/групп ИЛИ ссылки на посты',
    ],
    risks:
      'Реакции — самый «дешёвый» модуль, и именно им чаще всего добивают уставшие аккаунты. '
      + 'Усталость и распорядок общие для всех модулей, поэтому профиль, отработавший смену '
      + 'в другом месте, сюда уже не попадёт.',
    costModel: 'Списывается за действие по прайсу модуля. Токены ИИ не расходуются — генерации нет.',
  },

  blocks: [
    {
      id: 'accounts',
      title: 'Выберите аккаунты',
      purpose: 'Какими управляемыми аккаунтами ставятся реакции.',
      howItWorks:
        'Аккаунты перебираются по кругу. Занятый другой задачей не выдаётся; проблемные статусы, '
        + 'усталость, распорядок и суточный лимит реакций пропускаются с записью в лог.',
      api: { method: 'POST', path: '/api/modules/mass-react/tasks', fills: ['accountIds'] },
      params: ['accountIds'],
    },
    {
      id: 'targets',
      title: 'Цели',
      purpose: 'На что ставить реакции — на посты каналов или на конкретные посты по ссылкам.',
      howItWorks:
        'Если задан postUrls, работа идёт ТОЛЬКО по этим ссылкам, а channels и reactMode игнорируются. '
        + 'Если postUrls пуст, аккаунт вступает в случайный канал из channels, а какой пост брать — '
        + 'решает reactMode. Посты каналов из чёрного списка отсеиваются.',
      api: { method: 'POST', path: '/api/modules/mass-react/tasks', fills: ['channels', 'postUrls', 'reactMode', 'lastPostsCount'] },
      params: ['channels', 'postUrls', 'reactMode', 'lastPostsCount'],
    },
    {
      id: 'reactions',
      title: 'Реакции',
      purpose: 'Какие эмодзи ставятся и как часто.',
      howItWorks:
        'Эмодзи выбирается случайно из набора на каждое действие. Вероятность применяется один раз, '
        + 'перед отправкой реакции (до 18.08 в ветке каналов она проверялась дважды, и фактическая '
        + 'доля действий была ниже заданной).',
      api: { method: 'POST', path: '/api/modules/mass-react/tasks', fills: ['emojis', 'probability'] },
      params: ['emojis', 'probability'],
    },
    {
      id: 'modes',
      title: 'Режим работы',
      purpose: 'Чем ограничена задача — числом реакций или временем.',
      howItWorks: 'По количеству — до достижения цели; по времени — до истечения длительности.',
      api: { method: 'POST', path: '/api/modules/mass-react/tasks', fills: ['workMode', 'durationMinutes'] },
      params: ['workMode', 'durationMinutes'],
    },
    {
      id: 'limits',
      title: 'Лимиты',
      purpose: 'Сколько реакций поставить всего и сколько одним аккаунтом.',
      howItWorks: 'Фактическая цель — случайное число из [min, max], детерминированное по ID задачи.',
      api: { method: 'POST', path: '/api/modules/mass-react/tasks', fills: ['maxActions', 'minActions', 'maxPerAccount', 'minPerAccount'] },
      params: ['maxActions', 'minActions', 'maxPerAccount', 'minPerAccount'],
    },
    {
      id: 'protection',
      title: 'Защита аккаунтов',
      purpose: 'Множитель задержек и потолок вероятности действий.',
      howItWorks: 'Уровень защиты умножает задержки и ограничивает вероятность сверху.',
      api: { method: 'POST', path: '/api/modules/mass-react/tasks', fills: ['aiProtection', 'protectionLevel'] },
      params: ['aiProtection', 'protectionLevel'],
    },
    {
      id: 'timings',
      title: 'Тайминги и задержки',
      purpose: 'Паузы между реакциями и поведение при FloodWait.',
      howItWorks: 'Пауза = случайная из диапазона × множитель защиты × множитель пресета, но не меньше 5 секунд.',
      api: { method: 'POST', path: '/api/modules/mass-react/tasks', fills: ['delayPreset', 'delays'] },
      params: ['delayPreset', 'delays'],
    },
    {
      id: 'binding',
      title: 'Привязка',
      purpose: 'К какой цели относится задача и когда работа прекращается.',
      howItWorks: 'Просроченный дедлайн останавливает уже идущую задачу, а не только новые запуски.',
      api: { method: 'POST', path: '/api/modules/mass-react/tasks', fills: ['goalId', 'deadline'] },
      params: ['goalId', 'deadline'],
    },
  ],

  params: [
    {
      name: 'accountIds',
      block: 'accounts',
      title: 'Аккаунты',
      type: 'array',
      items: 'string',
      required: true,
      minItems: 1,
      purpose: 'ID управляемых аккаунтов, которыми ставятся реакции.',
      constraints: ['пустой список → отказ «Выберите хотя бы один аккаунт»'],
      examples: [['acc_1'], ['acc_1', 'acc_2']],
      storedAs: 'task.settings.accountIds',
    },
    {
      name: 'channels',
      block: 'targets',
      title: 'Каналы и группы',
      type: 'array',
      items: 'string',
      default: [],
      aliases: ['targets'],
      purpose: 'Каналы и группы, на свежие посты которых ставятся реакции.',
      constraints: [
        'обязателен, ЕСЛИ не задан postUrls — иначе запуск отклоняется',
        'полностью игнорируется, когда задан postUrls',
        'формат: @username или https://t.me/<username>',
      ],
      examples: [['@durov']],
      seeAlso: ['postUrls'],
      storedAs: 'task.settings.channels (сервер принимает и targets)',
    },
    {
      name: 'postUrls',
      block: 'targets',
      title: 'Ссылки на посты',
      type: 'array',
      items: 'string',
      default: [],
      purpose: 'Конкретные посты, на которые нужно поставить реакции.',
      constraints: [
        'формат https://t.me/<канал>/<номер поста> или https://t.me/c/<id>/<номер>',
        'имеет ПРИОРИТЕТ над channels: если список непустой, каналы не используются',
        'посты каналов из чёрного списка отбрасываются',
      ],
      examples: [['https://t.me/durov/342']],
      seeAlso: ['channels'],
      storedAs: 'task.settings.postUrls',
    },
    {
      name: 'reactMode',
      block: 'targets',
      title: 'Режим выбора поста',
      type: 'number',
      enum: [
        { value: 0, label: 'Мониторинг новых', means: 'Реагирует только на посты, вышедшие после того, как аккаунт впервые зашёл в канал в рамках этой задачи.' },
        { value: 1, label: 'Существующие посты', means: 'Реагирует на случайный пост из lastPostsCount последних.' },
      ],
      default: 0,
      purpose: 'На какие посты канала ставить реакции — только на новые или на N последних.',
      constraints: [
        '0 — мониторинг: первый заход в канал ТОЛЬКО запоминает последний пост и реакцию не ставит; '
        + 'дальше реагируем на посты, вышедшие после этого момента',
        '1 — существующие: берётся случайный из lastPostsCount последних постов',
        'планка «что уже было» живёт в памяти процесса: после рестарта она встаёт заново, '
        + 'и посты из времени простоя новыми не считаются',
        'игнорируется, когда задан postUrls',
      ],
      examples: [0, 1],
      seeAlso: ['lastPostsCount', 'postUrls'],
      storedAs: 'task.settings.reactMode',
    },
    {
      name: 'lastPostsCount',
      block: 'targets',
      title: 'Сколько последних постов',
      type: 'number',
      min: 1,
      max: 20,
      default: 3,
      purpose: 'Глубина выборки в режиме «существующие посты».',
      constraints: [
        'работает только при reactMode = 1',
        'значения вне 1–20 обрезаются до границ; 0 и мусор дают 3',
        'один аккаунт ставит не больше одной реакции на один пост, разные аккаунты — ставят',
      ],
      examples: [2, 3, 5],
      effectiveWhen: { field: 'reactMode', equals: 1 },
      seeAlso: ['reactMode'],
      storedAs: 'task.settings.lastPostsCount',
    },
    {
      name: 'emojis',
      block: 'reactions',
      title: 'Набор эмодзи',
      type: 'array',
      items: 'string',
      default: ['👍', '❤️', '🔥'],
      purpose: 'Из чего случайно выбирается реакция на каждое действие.',
      constraints: [
        'пустой список = используется набор по умолчанию 👍 ❤️ 🔥',
        'эмодзи должен быть разрешён в канале, иначе Telegram отклонит реакцию',
      ],
      examples: [['👍'], ['👍', '🔥', '🎉']],
      storedAs: 'task.settings.emojis',
    },
    {
      name: 'probability',
      block: 'reactions',
      title: 'Вероятность реакции',
      type: 'integer',
      default: 50,
      min: 0,
      max: 100,
      unit: '%',
      purpose: 'С какой вероятностью подходящий пост получит реакцию.',
      constraints: [
        'при aiProtection = true потолок урезается уровнем защиты: консервативный ≤25 %, сбалансированный ≤45 %, агрессивный без ограничения',
        'при работе по каналам проверка выполняется ДВАЖДЫ — фактическая доля примерно равна квадрату заданной',
      ],
      examples: [30, 50, 100],
      seeAlso: ['aiProtection', 'protectionLevel'],
      storedAs: 'task.settings.probability',
    },
    {
      name: 'workMode',
      block: 'modes',
      title: 'Режим работы',
      type: 'integer',
      default: 0,
      enum: [
        { value: 0, label: 'По количеству', means: 'Задача идёт, пока не достигнута цель по числу реакций.' },
        { value: 1, label: 'По времени', means: 'Задача идёт, пока не истечёт durationMinutes.' },
      ],
      purpose: 'Чем ограничена задача.',
      constraints: ['при workMode = 1 обязателен durationMinutes'],
      seeAlso: ['durationMinutes', 'maxActions'],
      storedAs: 'task.settings.workMode',
    },
    {
      name: 'durationMinutes',
      block: 'modes',
      title: 'Длительность',
      type: 'integer',
      default: 60,
      min: 1,
      unit: 'мин',
      requiredWhen: { workMode: 1 },
      effectiveWhen: { workMode: 1 },
      purpose: 'Сколько задача работает в режиме «По времени».',
      constraints: [
        'трактуется как МАКСИМУМ: фактическая длительность — случайное число из [min, durationMinutes], '
        + 'где min задаёт уровень защиты (60 / 45 / 30 минут)',
      ],
      seeAlso: ['workMode', 'protectionLevel'],
      storedAs: 'task.settings.durationMinutes',
    },
    {
      name: 'maxActions',
      block: 'limits',
      title: 'Макс. реакций',
      type: 'integer',
      default: 100,
      min: 1,
      aliases: ['maxComments'],
      purpose: 'Верхняя граница числа реакций за задачу.',
      constraints: ['должен быть ≥ minActions'],
      examples: [20, 200],
      seeAlso: ['minActions'],
      storedAs: 'task.settings.maxActions',
    },
    {
      name: 'minActions',
      block: 'limits',
      title: 'Мин. реакций',
      type: 'integer',
      default: 0,
      min: 0,
      aliases: ['minComments'],
      purpose: 'Нижняя граница цели задачи. Фактическая цель — случайное число из [min, max].',
      constraints: ['должен быть ≤ maxActions'],
      seeAlso: ['maxActions'],
      storedAs: 'task.settings.minActions',
    },
    {
      name: 'maxPerAccount',
      block: 'limits',
      title: 'Макс. на аккаунт',
      type: 'integer',
      default: 0,
      min: 0,
      purpose: 'Потолок реакций одним аккаунтом за задачу.',
      constraints: [
        '0 = ограничения на аккаунт нет',
        'независимо от него действует суточный лимит реакций §6 у аккаунта (по умолчанию 200)',
      ],
      storedAs: 'task.settings.maxPerAccount',
    },
    {
      name: 'minPerAccount',
      block: 'limits',
      title: 'Мин. на аккаунт',
      type: 'integer',
      default: 0,
      min: 0,
      effectiveWhen: { maxPerAccount: '*' },
      purpose: 'Нижняя граница цели на один аккаунт.',
      constraints: ['должен быть ≤ maxPerAccount', 'работает только когда maxPerAccount > 0'],
      storedAs: 'task.settings.minPerAccount',
    },
    {
      name: 'aiProtection',
      block: 'protection',
      title: 'ИИ-защита',
      type: 'boolean',
      default: true,
      purpose: 'Включает потолок вероятности из уровня защиты.',
      seeAlso: ['protectionLevel', 'probability'],
      storedAs: 'task.settings.aiProtection',
    },
    {
      name: 'protectionLevel',
      block: 'protection',
      title: 'Уровень защиты',
      type: 'integer',
      default: 1,
      enum: [
        { value: 0, label: 'Консервативный', means: 'Задержки ×1.8, вероятность ≤25 %, минимальная длительность 60 мин.' },
        { value: 1, label: 'Сбалансированный', means: 'Задержки ×1, вероятность ≤45 %, минимальная длительность 45 мин.' },
        { value: 2, label: 'Агрессивный', means: 'Задержки ×0.75, вероятность без ограничения, минимальная длительность 30 мин.' },
      ],
      purpose: 'Насколько осторожно ведёт себя аккаунт.',
      constraints: ['ВНИМАНИЕ: нумерация ОБРАТНА delayPreset — здесь 0 самый безопасный'],
      seeAlso: ['delayPreset', 'probability'],
      storedAs: 'task.settings.protectionLevel',
    },
    {
      name: 'delayPreset',
      block: 'timings',
      title: 'Пресет темпа',
      type: 'integer',
      default: 1,
      enum: [
        { value: 0, label: 'Агрессивный', means: 'Паузы ×0.6, длительность ×0.75.' },
        { value: 1, label: 'Сбалансированный', means: 'Базовые задержки ×1.' },
        { value: 2, label: 'Консервативный', means: 'Паузы ×1.8, длительность ×1.5.' },
        { value: 3, label: 'Custom', means: 'Задержки берутся как заданы, без масштабирования.' },
      ],
      purpose: 'Масштабирует все задержки задачи.',
      constraints: ['ВНИМАНИЕ: нумерация ОБРАТНА protectionLevel — здесь 0 самый быстрый'],
      seeAlso: ['protectionLevel', 'delays'],
      storedAs: 'task.settings.delayPreset',
    },
    {
      name: 'delays',
      block: 'timings',
      title: 'Задержки',
      type: 'object',
      purpose: 'Базовые интервалы, к которым применяются множители защиты и пресета.',
      constraints: ['паузы перед вступлением у этого модуля нет — вступление идёт без отдельной задержки'],
      properties: [
        {
          name: 'action',
          title: 'Пауза перед реакцией',
          type: 'array',
          items: 'number',
          minItems: 2,
          maxItems: 2,
          default: [30, 120],
          unit: 'с',
          purpose: 'Диапазон [мин, макс] паузы перед постановкой реакции.',
          constraints: ['фактическая пауза — случайная из диапазона × множители, но не меньше 5 секунд'],
        },
        {
          name: 'floodWait',
          title: 'Запас после FloodWait',
          type: 'number',
          default: 120,
          min: 0,
          unit: 'с',
          purpose: 'Сколько ждать сверх длительности, которую вернул Telegram.',
        },
        {
          name: 'floodQuarantine',
          title: 'FloodWait до карантина',
          type: 'integer',
          default: 3,
          min: 1,
          purpose: 'Сколько FloodWait подряд выдерживает аккаунт до отправки в карантин.',
        },
      ],
      storedAs: 'task.settings.delays',
    },
    {
      name: 'goalId',
      block: 'binding',
      title: 'Цель',
      type: 'string',
      purpose: 'Цель, к которой относится задача.',
      constraints: [
        'на содержание реакций не влияет — генерации у модуля нет',
        'используется для дедлайна и отчётности; просроченная цель останавливает задачу',
      ],
      seeAlso: ['deadline'],
      storedAs: 'task.settings.goalId',
    },
    {
      name: 'deadline',
      block: 'binding',
      title: 'Дедлайн',
      type: 'string',
      pattern: '^\\d{4}-\\d{2}-\\d{2}$',
      purpose: 'Дата, после которой работа по задаче прекращается.',
      constraints: [
        'формат YYYY-MM-DD; дедлайн включает указанный день целиком',
        'приезжает из кампании; если не задан — берётся дедлайн цели по goalId',
        'останавливает УЖЕ ИДУЩУЮ задачу',
      ],
      examples: ['2026-09-01'],
      seeAlso: ['goalId'],
      storedAs: 'task.settings.deadline',
    },
  ],

  presets: [
    {
      param: 'delayPreset',
      title: 'Пресет темпа',
      source: 'server/lib/protection.js — PRESET_MUL',
      values: [
        { value: 0, label: 'Агрессивный', multiplier: 0.6, means: 'Паузы ×0.6, длительность ×0.75.', useWhen: 'прогретые «расходные» аккаунты' },
        { value: 1, label: 'Сбалансированный', multiplier: 1, means: 'Базовые задержки.', useWhen: 'повседневная работа' },
        { value: 2, label: 'Консервативный', multiplier: 1.8, means: 'Паузы ×1.8, длительность ×1.5.', useWhen: 'новые и дорогие аккаунты' },
        { value: 3, label: 'Custom', multiplier: 1, means: 'Без масштабирования.', useWhen: 'ручная настройка' },
      ],
    },
    {
      param: 'protectionLevel',
      title: 'Уровень защиты',
      source: 'server/lib/protection.js — LEVEL_MUL + effectiveProbability; server/lib/workModeDuration.js',
      values: [
        { value: 0, label: 'Консервативный', multiplier: 1.8, probabilityCap: 25, minDurationMinutes: 60, means: 'Задержки ×1.8, вероятность ≤25 %.' },
        { value: 1, label: 'Сбалансированный', multiplier: 1, probabilityCap: 45, minDurationMinutes: 45, means: 'Задержки ×1, вероятность ≤45 %.' },
        { value: 2, label: 'Агрессивный', multiplier: 0.75, probabilityCap: 100, minDurationMinutes: 30, means: 'Задержки ×0.75, вероятность без ограничения.' },
      ],
    },
  ],

  examples: [
    {
      title: 'Реакции на конкретные посты',
      when: 'нужно поддержать несколько известных публикаций',
      input: {
        accountIds: ['acc_1', 'acc_2'],
        postUrls: ['https://t.me/durov/342', 'https://t.me/durov/343'],
        emojis: ['👍', '🔥'],
        maxActions: 10,
        probability: 100,
        protectionLevel: 1,
        delayPreset: 1,
      },
    },
    {
      title: 'Фоновая активность по каналам',
      when: 'нужно ровное присутствие на свежих постах нескольких каналов',
      input: {
        accountIds: ['acc_1', 'acc_2', 'acc_3'],
        channels: ['@channel_one', '@channel_two'],
        emojis: ['👍', '❤️', '🔥'],
        workMode: 1,
        durationMinutes: 480,
        maxPerAccount: 15,
        probability: 70,
        protectionLevel: 0,
        delayPreset: 2,
      },
    },
  ],

  contract: {
    sources: [
      { file: 'server/modules/workers.js', symbols: ['runMassReact', 'targets', 'goalExpired'] },
      { file: 'server/lib/targets.js', symbols: ['resolveTotalTarget', 'resolvePerAccountTarget'] },
      { file: 'server/lib/accountRunner.js', symbols: ['totalLimitReached', 'perAccountLimitReached', 'handleFlood'] },
      { file: 'server/lib/workModeDuration.js', symbols: ['resolveDurationPeriodMinutes'] },
    ],
    ignore: ['initiator', 'userId'],
  },
}
